


import sequana.snakemake as sm

# find all fastq files and parse them through fastqc



#fastqc_wc = ["fastqc/{dataset}", sm.get_filenames("fastq_raw/*fastq.gz")]
#fastqc_input = expand(fastqc_wc[0], dataset=fastqc_wc[1])

fastqc_data = expand("fastqc_results/{dataset}", dataset=sm.get_filenames("fastq_raw/*fastq.gz"))




rule fastqc_output:
    input:
        expand("fastqc_results/{dataset}_fastqc.html",
            dataset=["Hm2_GTGAAA_L005_R1_001", "Hm2_GTGAAA_L005_R2_001"])



# fastq_results must be created for now
rule fastqc:
    input: "fastq_raw/{dataset}.fastq.gz"
    output: "fastqc_results/{dataset}_fastqc.html"
    params: dir="fastqc_results"
    threads: 2
    log: "{dataset}.log"
    run: 
        shell("fastqc -t {threads} --outdir {params.dir} -f fastq {input} > {params.dir}/{log}")



