include: sm.modules['dag']     # Create DAG file
include: sm.modules['conda']   # Create requirements.txt(dependencies)

import sequana.snaketools as sm
cfg = sm.SequanaConfig.from_dict(config)
PROJECT = cfg.PROJECT



rule report_phix_removal:
    input:
        dag = "dag.svg",
        conda = "%s/requirements.txt" % PROJECT,
        bwa_bam_to_fastq = "%s/bwa_bam_to_fastq/bwa_mem_stats.json" % PROJECT,
        fastqc = "%s/fastqc/fastqc.done" % PROJECT,
        fastq_stats = "%s/logs/fastq_stats.done" % PROJECT
    output:
        "%s/index.html" % PROJECT,
        "%s/bwa_mem.html" % PROJECT,
        "%s/dag.svg" % PROJECT,
    params:
        outdir = PROJECT
    run:
        from sequana import report_main
        from sequana import report_phix
        from sequana import report_fastqc

        # Main page
        s = report_main.SequanaReport(directory=params.outdir)

        for this in cfg.DATASET:
            s.jinja['output'] = cfg.DATASET

        s.create_report()

        # Phix page
        s = report_phix.PhixReport(output_filename="bwa_mem.html",
                directory=params.outdir)
        s.input_filename = "%s/bwa_bam_to_fastq/bwa_mem_stats.json" % PROJECT
        s.create_report()

        s = report_fastqc.FastQCReport(directory=params.outdir)
        s.create_report()

        shell("cp Snakefile %s/" % params.outdir)
        shell("mv {input.dag} %s/" % params.outdir)


