import sequana.snaketools as sm
from sequana import tools

filefact = sm.FileFactory(config['samples']['glob'])
info = tools.FastqFactory(filefact.basenames)

keys = info.keys()
assert len(keys) == 1
project_name = list(keys)[0]


rule bwa_bam_to_fastq:
    message: """
    -- Extracting the fastq from the BAM/SAM files
    -- information saved in {log}
    """
    input:
        bam = "bwa_phix/%s.bam" % project_name,
    params:
        wkdir = "bwa_phix",
    output:
        "bwa_phix/phix_stats.json"
    threads: 1
    run:
        import json
        from sequana.tools import bam_to_mapped_unmapped_fastq as bam2fastq
        stats = bam2fastq(input["bam"])
        json.dump(stats, open("%s/phix_stats.json" % params.wkdir, "w"))

        # zip the fastq files
        import glob
        tozip = glob.glob("%s/*.fastq" % params.wkdir)
        for filename in tozip:
            shell("pigz -f %s " % filename)



