"""
Author: Thomas Cokelaer
Affiliation: Institut Pasteur
Aim: Find Fix contaminant in the fastq
Data: paired end or single reads
Run: snakemake -s Snakefile
Changelog:

Config file needs to be edited to (1) set the input files and (2) the project
name

"""
import sequana
from sequana import snaketools as sm

# This must be defined before the include 
configfile: "config.yaml"

from sequana.snaketools import SequanaConfig, FileFactory
cfg = SequanaConfig(config)


# Optional for testing
if config['fastq_sampling']['enable'] is True:
    include: sm.modules['fastq_sampling']
    # TODO set FILE1 and FILE2 automatically
    FILE1 = cfg.PROJECT + "_R1_001.fastq.gz"
    FILE2 = cfg.PROJECT + "_R2_001.fastq.gz"
    config['samples']['file1'] = "fastq_sampling/%s" % FILE1
    config['samples']['file2'] = "fastq_sampling/%s" % FILE2

include: sm.modules['bwa_mem']           # Search for the Fix
include: sm.modules['bwa_bam_to_fastq']  # Save mapped and unmapped data in bwa_phix/
include: sm.modules['fastqc']            # quality control
include: sm.modules['fastq_stats']
include: sm.modules['report_phix_removal']# Report + DAG + CONDA 



#localrules: dag
#ruleorder: fastq_sampling > bwa_mem > bwa_bam_to_fastq > fastqc > fastq_stats


# check that all rules will have the required parameters in the config


#sm.sequana_check_config(config, globals())

cfg = sm.SequanaConfig.from_dict(config)




rule all:
    input: "%s/index.html" % config["project"],
    version: sequana.version





