"""


Takes fastq in fastq_sampling if possible, otherwise
takes original data sets in fastq_raw

Then, the code does::

    bwa index reference
    bwa mem -t {threads} -M reference fastq_files > output.sam
    samtools view -bT reference output.sam -o output.bam
"""
import glob
from sequana import snaketools as sm
from sequana import tools



# -- module definition

filefact = sm.FileFactory(config['samples']['glob'])

info = tools.FastqFactory(filefact.basenames)

keys = info.keys()
assert len(keys) == 1
project_name = list(keys)[0]


rule bwa_phix:
    message: """
    -- Running bwa index and bwa mem
    -- information saved in {log}
    """
    input:
        reference = config['bwa_phix']['reference'],
        data = expand("fastq_raw/{dataset}", dataset=filefact.basenames)
    params:
        # fastq here must be a string not a list hence the join
        wkdir = "bwa_phix",
        fastq = " ".join(['fastq_raw/%s'%x for x in filefact.basenames])
    output:
        bam = "bwa_phix/%s.bam"% project_name
    log: "logs/bwa_phix.log"
    threads: 4
    shell:
        """
        # a local copy of contaminant from input to bwa_contaminant
        cp {input.reference} {params.wkdir}

        # Create index
        bwa index {params.wkdir}/{input.reference}

        # Run bwa
        bwa mem -t {threads}  -M {params.wkdir}/{input.reference} {params.fastq} \
            |  samtools view -bT {params.wkdir}/{input.reference} -> {output.bam}
        """


rule bwa_phix_cleanup:
    params:
        wkdir= "bwa_phix"

